services:
  - type: web
    name: alfa-analytics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run web/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: DADATA_API_KEY
        sync: false
